"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { Flame, Layers, MapPin, Plus, Minus, Crosshair, Wind, Droplets, Thermometer, ChevronRight, Info, Mountain, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { NativeSelect } from '@/components/ui/native-select';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { cells, aggregate, sample, project, coast, cities, nearest, category, colors, type Cell } from '@/lib/wildfire';
const layers=[{id:'risk',name:'Wildfire risk',sub:'Relative index · 0–100',icon:Flame},{id:'temperature',name:'Temperature',sub:'Daily maximum · °C',icon:Thermometer},{id:'dryness',name:'Fuel dryness',sub:'Sample index · 0–100',icon:Layers},{id:'wind',name:'Wind speed',sub:'Daily average · km/h',icon:Wind}] as const;
type Layer=typeof layers[number]['id'];
function tone(layer:Layer,value:number){const v=layer==='temperature'?(value-16)*4:layer==='wind'?value*2.5:value;return colors[Math.min(3,Math.max(0,Math.floor(v/25)))];}
const dates=['Tue 15','Wed 16','Thu 17','Fri 18','Sat 19','Sun 20','Mon 21'];
export default function Home(){
 const [day,setDay]=useState(0),[layer,setLayer]=useState<Layer>('risk'),[resolution,setResolution]=useState('fine'),[labels,setLabels]=useState(true),[mode,setMode]=useState('map');
 const [selectedId,setSelectedId]=useState(nearest(cells,39.76,-121.61).id),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number,y:number,px:number,py:number,moved:boolean}|null>(null);
 const visible=useMemo(()=>resolution==='fine'?cells:aggregate(cells),[resolution]);
 const base=cells.find(c=>c.id===selectedId)??cells[0],selected=visible.find(c=>c.id===base.id||c.children?.some(x=>x.id===base.id))??nearest(visible,base.lat,base.lon);
 const data=sample(selected,day),trend=dates.map((_,d)=>sample(selected,d).risk),activeLayer=layers.find(l=>l.id===layer)!;
 const average=Math.round(cells.reduce((s,c)=>s+sample(c,day).risk,0)/cells.length),elevated=visible.filter(c=>sample(c,day).risk>=50).length;
 const place=cities.reduce((a,b)=>Math.hypot(a.lat-selected.lat,(a.lon-selected.lon)*.77)<Math.hypot(b.lat-selected.lat,(b.lon-selected.lon)*.77)?a:b);
 function pick(c:Cell){setSelectedId(c.children?nearest(c.children,c.lat,c.lon).id:c.id);}
 function cityPick(name:string){const c=cities.find(c=>c.name===name);if(c){setSelectedId(nearest(cells,c.lat,c.lon).id);setPan({x:0,y:0});setZoom(1);}}
 function move(dx:number,dy:number){setPan(p=>({x:Math.max(-600,Math.min(600,p.x+dx)),y:Math.max(-500,Math.min(500,p.y+dy))}));}
 function setScale(n:number){setZoom(Math.max(1,Math.min(3,n)));}
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'configure_wildfire_view',description:'Select a sample location, day, and map layer in Wildfire Atlas.',inputSchema:{type:'object',properties:{location:{type:'string',enum:cities.map(c=>c.name)},day:{type:'integer',minimum:0,maximum:6},layer:{type:'string',enum:layers.map(l=>l.id)}},required:['location','day','layer'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const x=input as {location:string,day:number,layer:Layer};if(!x||!cities.some(c=>c.name===x.location)||!Number.isInteger(x.day)||x.day<0||x.day>6||!layers.some(l=>l.id===x.layer))throw new Error('Choose a listed location, day 0–6, and supported layer.');cityPick(x.location);setDay(x.day);setLayer(x.layer);setResolution('fine');setMode('map');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const c=cities.find(c=>c.name===x.location)!;return {location:x.location,day:x.day,layer:x.layer,sampleData:true,risk:sample(nearest(cells,c.lat,c.lon),x.day).risk};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 const map=<div className="map-surface"><div className="map-caption"><span className="smallcaps">NORTHERN CALIFORNIA</span><span>Sample coverage · {visible.length} cells</span></div>
 <svg ref={svg} className="geo-map" viewBox="0 0 850 680" aria-label="Northern California interactive sample map. Select a colored cell; drag to pan. Arrow keys pan the map." tabIndex={0}
 onKeyDown={e=>{const d:{[k:string]:number[]}={ArrowLeft:[30,0],ArrowRight:[-30,0],ArrowUp:[0,30],ArrowDown:[0,-30]};if(e.target===svg.current&&d[e.key]){e.preventDefault();move(d[e.key][0],d[e.key][1]);}}}
 onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>4)d.moved=true;const rect=e.currentTarget.getBoundingClientRect(),scale=Math.min(rect.width/850,rect.height/680);if(d.moved)setPan({x:Math.max(-600,Math.min(600,d.px+dx/scale)),y:Math.max(-500,Math.min(500,d.py+dy/scale))});}}
 onPointerUp={e=>{const d=drag.current;if(d&&!d.moved){const rect=e.currentTarget.getBoundingClientRect(),scale=Math.min(rect.width/850,rect.height/680),x=((e.clientX-rect.left-(rect.width-850*scale)/2)/scale-425-pan.x)/zoom+425,y=((e.clientY-rect.top-(rect.height-680*scale)/2)/scale-340-pan.y)/zoom+340;const hit=visible.find(c=>{const p=project(c.lon,c.lat);return Math.abs(x-p[0])<c.step*145/2&&Math.abs(y-p[1])<c.step*150/2;});if(hit)pick(hit);}drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <rect width="850" height="680" fill="#0c1d27"/><g transform={`translate(${425+pan.x} ${340+pan.y}) scale(${zoom}) translate(-425 -340)`}>
 <path d={coast} fill="#213337" stroke="#6b827e" strokeWidth="1.4"/>
 {[38,39,40,41,42].map(lat=><g key={lat}><line x1="20" x2="830" y1={project(-124,lat)[1]} y2={project(-124,lat)[1]} stroke="#587072" strokeDasharray="3 8" opacity=".22"/><text x="24" y={project(-124,lat)[1]-8} fill="#829a9f" fontSize="13">{lat}°N</text></g>)}
 {[-124,-123,-122,-121,-120].map(lon=><g key={lon}><line y1="15" y2="650" x1={project(lon,40)[0]} x2={project(lon,40)[0]} stroke="#587072" strokeDasharray="3 8" opacity=".22"/><text x={project(lon,40)[0]+5} y="651" fill="#829a9f" fontSize="13">{Math.abs(lon)}°W</text></g>)}
 <text x="105" y="400" fill="#63808f" fontSize="17" letterSpacing="4" transform="rotate(-60 105 400)">PACIFIC OCEAN</text><text x="702" y="330" fill="#8a9b9e" fontSize="15" letterSpacing="4" transform="rotate(35 702 330)">NEVADA</text>
 {visible.map(c=>{const p=project(c.lon,c.lat),value=sample(c,day)[layer];return <rect key={c.id} role="button" tabIndex={c.id===selected.id?0:-1} aria-label={`Inspect cell ${c.id}, ${c.lat.toFixed(2)} N, ${Math.abs(c.lon).toFixed(2)} W`} x={p[0]-c.step*145/2+1} y={p[1]-c.step*150/2+1} width={c.step*145-2} height={c.step*150-2} rx="2" fill={tone(layer,value)} opacity={c.id===selected.id?1:.72} className="map-cell" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(c);}if(e.key.startsWith('Arrow')){e.preventDefault();const dx=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0,dy=e.key==='ArrowUp'?1:e.key==='ArrowDown'?-1:0;const target=nearest(visible,c.lat+dy*c.step,c.lon+dx*c.step);pick(target);requestAnimationFrame(()=>{svg.current?.querySelector<SVGRectElement>(`[aria-label^="Inspect cell ${target.id},"]`)?.focus();});}}}><title>{`${activeLayer.name}: ${value} · ${c.lat.toFixed(2)}°N, ${Math.abs(c.lon).toFixed(2)}°W`}</title></rect>;})}
 {labels&&cities.map(c=>{const p=project(c.lon,c.lat);return <g className="city-label" key={c.name} transform={`translate(${p[0]},${p[1]})`} pointerEvents="none"><circle r="3.5" fill="#f3f6f5" stroke="#14282c" strokeWidth="2"/><text x={c.name==='Chico'?-9:9} textAnchor={c.name==='Chico'?'end':'start'} y="-8" fontSize="15" fill="#f1f5f2" stroke="#11252b" strokeWidth="4" paintOrder="stroke" fontWeight="600">{c.name}</text></g>;})}
 <g pointerEvents="none" transform={`translate(${project(selected.lon,selected.lat).join(' ')})`}><rect x={-selected.step*145/2-2} y={-selected.step*150/2-2} width={selected.step*145+4} height={selected.step*150+4} fill="none" stroke="white" strokeWidth="2.5" rx="3"/><circle r="5" fill="white" stroke="#1b2529" strokeWidth="2"/></g></g></svg>
 <div className="map-tools"><Button variant="outline" size="icon" aria-label="Zoom in" onClick={()=>setScale(zoom+.35)} disabled={zoom>=3}><Plus/></Button><Button variant="outline" size="icon" aria-label="Zoom out" onClick={()=>setScale(zoom-.35)} disabled={zoom<=1}><Minus/></Button><Button variant="outline" size="icon" aria-label="Reset map view" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><Crosshair/></Button><span>{zoom.toFixed(1)}×</span></div><div className="north">N<span>↑</span></div>
 <div className="map-legend"><strong>{activeLayer.name}</strong><div className="legend-swatches">{colors.map((c,i)=><span key={c}><i style={{background:c}}/>{layer==='risk'?['Low','Moderate','High','Very high'][i]:layer==='temperature'?['≤22','23–28','29–34','35+ °C'][i]:layer==='wind'?['0–9','10–19','20–29','30+ km/h'][i]:['0–24','25–49','50–74','75–100'][i]}</span>)}</div></div><div className="map-footnote">Simplified basemap · Sample grid · Drag to pan</div></div>;
 return <main className="atlas"><header className="app-header"><div className="brand"><span className="brand-mark"><Flame size={23}/></span><div><h1>Wildfire <b>Atlas</b></h1><p>RISK EXPLORER</p></div></div><div className="header-region"><MapPin size={16}/> Northern California <span>/</span> September 2026</div><span className="private-badge"><Info size={14}/> Sample prototype</span></header>
 <div className="sample-banner"><Info size={16}/><span><strong>Sample data</strong> · Illustrative risk scores and weather, not live forecasts or a trained model. For prototype exploration only.</span></div>
 <div className="workspace"><aside className="controls"><div className="control-section"><p className="eyebrow">EXPLORER</p><h2>Explore the region</h2><label htmlFor="location">Jump to a location</label><NativeSelect id="location" value="" onChange={e=>cityPick(e.target.value)}><option value="" disabled>Select a sample location</option>{cities.map(c=><option key={c.name}>{c.name}</option>)}</NativeSelect></div>
 <div className="control-section"><h3><Layers size={16}/> Map layers</h3><div className="layer-options">{layers.map(l=><Button variant="ghost" className={`layer-option ${layer===l.id?'chosen':''}`} key={l.id} aria-pressed={layer===l.id} onClick={()=>setLayer(l.id)}><l.icon size={18}/><span><strong>{l.name}</strong><small>{l.sub}</small></span><span className="radio-dot"/></Button>)}</div></div>
 <div className="control-section"><label htmlFor="resolution">Spatial resolution</label><NativeSelect id="resolution" value={resolution} onChange={e=>setResolution(e.target.value)}><option value="fine">0.2° cells · ~20 km</option><option value="coarse">0.4° cells · ~40 km</option></NativeSelect><p className="hint">Larger cells average the underlying sample cells.</p><div className="switch-row"><label htmlFor="labels">Place labels</label><Switch id="labels" checked={labels} onCheckedChange={setLabels}/></div></div>
 <div className="coverage"><Mountain size={20}/><strong>One region. Multiple views.</strong><p>Select a map cell to inspect its conditions, then move through the sample forecast.</p><span>38–42° N · 120–124° W</span></div></aside>
 <section className="main-panel"><div className="view-header"><div><p className="eyebrow">SPATIAL INTELLIGENCE</p><h2>{mode==='map'?'Risk across the landscape':'Seven-day outlook'}</h2></div><Tabs value={mode} onValueChange={setMode}><TabsList aria-label="Prediction view"><TabsTrigger value="map">Map</TabsTrigger><TabsTrigger value="trend">Time series</TabsTrigger></TabsList></Tabs></div>
 <div className="summary-strip"><div><span>Regional risk index</span><strong>{average}<small> / 100</small></strong></div><div><span>High / very high cells</span><strong>{elevated}<small> / {visible.length}</small></strong></div><div><span>Selected sample date</span><strong className="date-summary">{15+day} Sep 2026</strong></div></div>
 {mode==='map'?map:<div className="trend-view"><p className="eyebrow">SELECTED CELL · NEAR {place.name.toUpperCase()}</p><h3>How risk changes over time</h3><p>The same location, seven illustrative daily predictions.</p><div className="large-chart" aria-label="Seven day sample risk scores">{trend.map((r,d)=><button key={d} aria-label={`${dates[d]} September: risk ${r}`} aria-pressed={day===d} onClick={()=>setDay(d)}><span>{r}</span><i style={{height:`${r*2.2}px`,background:tone('risk',r)}}/><small>{dates[d]}</small></button>)}</div><div className="chart-baseline">Relative risk index · 0–100 · zero baseline</div><div className="trend-note"><Info size={18}/><p>These values demonstrate a changing forecast using sample heat, wind, humidity, and fuel conditions. They are not estimates of fire probability.</p></div></div>}
 <div className="timeline"><div className="timeline-heading"><span><CalendarDays size={17}/> Sample forecast</span><strong>{dates[day]} Sep</strong><small>15–21 September 2026</small></div><Slider aria-label="Sample forecast day" min={0} max={6} step={1} value={[day]} onValueChange={v=>setDay(v[0])}/><div className="date-ticks">{dates.map((d,i)=><button key={d} className={day===i?'selected':''} onClick={()=>setDay(i)} aria-label={`Select ${d} September`}>{d}</button>)}</div></div></section>
 <aside className="inspector" aria-label="Selected location details"><p className="eyebrow">LOCATION INSIGHT</p><h2>Near {place.name}</h2><p className="coordinates"><MapPin size={14}/>{selected.lat.toFixed(2)}° N, {Math.abs(selected.lon).toFixed(2)}° W</p><div className="cell-tag">Cell {selected.id} · {resolution==='fine'?'0.2°':'0.4°'} grid</div>
 <div className="risk-card" aria-live="polite"><div className="risk-card-heading"><span>Wildfire risk index</span><Flame size={19}/></div><div className="score" data-testid="selected-risk">{data.risk}<small>/100</small></div><span className="risk-label">{category(data.risk)}</span><div className="risk-meter">{colors.map(c=><span style={{background:c}} key={c}/>)}<i style={{left:`${data.risk}%`}}/></div><div className="risk-range"><span>Low</span><span>Very high</span></div><p>{15+day} September 2026 · Sample prediction</p></div>
 <section className="conditions"><h3>Contributing conditions</h3><div><Thermometer/><span>Max. temperature</span><strong>{data.temperature}°C</strong></div><div><Wind/><span>Average wind</span><strong>{data.wind} km/h</strong></div><div><Droplets/><span>Relative humidity</span><strong>{data.humidity}%</strong></div><div><Layers/><span>Fuel dryness index</span><strong>{data.dryness}/100</strong></div></section>
 <section className="mini-trend"><div><h3>7-day risk trend</h3><Button variant="ghost" size="sm" aria-label="Open time series" onClick={()=>setMode('trend')}><ChevronRight/></Button></div><div className="spark-bars">{trend.map((r,d)=><button key={d} aria-label={`Trend day ${d+1}: risk ${r}`} onClick={()=>setDay(d)} aria-pressed={day===d}><i style={{height:`${r*.7}px`,background:day===d?'#d98544':'#536560'}}/><small>{15+d}</small></button>)}</div></section>
 <details className="method"><summary>About the sample data</summary><p>Deterministic synthetic conditions on a latitude/longitude grid. Risk combines heat, wind, low humidity and dry fuel; it is not a probability. Low: 0–24, moderate: 25–49, high: 50–74, very high: 75–100. Coarse cells average fine-cell values. The regional index always averages fine cells. Boundaries are simplified; no live feeds or operational forecasts are connected.</p></details></aside></div>
 <footer><span>WILDFIRE ATLAS <span className="footer-divider">/</span> Prototype workspace</span><span>All risk and environmental layers use sample data</span></footer></main>;
}
